# -*- coding: utf-8 -*-
"""「A090H314.ipynb」的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1moR0Fv1-5K8uRRhPDb4jGo62x8z8gdXa

# HASH 雜湊函數
A090H314
1005
- md5
- sha1



- linux指令
- md5sum
- Colab使用方式 : !md5sum 檔案名稱
"""

!md5sum --help

!echo Deathsparklez > 1005.txt

!cat 1005.txt

!md5sum 1005.txt

!echo deathsparklez > 1005a.txt

!cat 1005a.txt

!md5sum 1005a.txt